import { ApiProperty } from '@nestjs/swagger';
import {
  IsNotEmpty,
  Length,
  Matches,
  IsOptional,
  IsString,
  IsPhoneNumber,
  IsDate,
  IsEmail,
  IsBoolean,
} from 'class-validator';

export class UpdatePayoutDetailsDTO {
  @ApiProperty({ 
    description: 'The name of the bank',
    example: 'Guaranty Trust Bank'
  })
  @IsString()
  @IsNotEmpty()
  bankName: string;

  @ApiProperty({ 
    description: 'The account number of the account holder',
    example: '0123456789'
  })
  @IsString()
  @IsNotEmpty()
  @Length(10, 10, { message: 'Account number must be 10 digits' })
  @Matches(/^\d+$/, { message: 'Account number must contain only digits' })
  accountNumber: string;

  @ApiProperty({ 
    description: 'The name of the account holder',
    example: 'John Chukwuma'
  })
  @IsString()
  @IsNotEmpty()
  accountName: string;

  @ApiProperty({ 
    description: 'one time password',
    example: '123456'
  })
  @IsString()
  @IsNotEmpty()
  otp: string;
}

export class UpdateUserDTO {
  @ApiProperty({
    description: 'Unique username chosen by the user',
    required: false,
    example: 'john_doe'
  })
  @IsOptional()
  @IsString()
  username?: string;

  @ApiProperty({
    description: 'Display name of the user',
    required: false,
    example: 'John Doe'
  })
  @IsOptional()
  @IsString()
  display_name?: string;

  @ApiProperty({
    description: 'Short bio or description about the user',
    required: false,
    example: 'Digital creator passionate about tech and design'
  })
  @IsOptional()
  @IsString()
  bio?: string;

  @ApiProperty({
    description: 'Phone number of the user in Nigerian format',
    required: false,
    example: '+2348012345678'
  })
  @IsOptional()
  @IsPhoneNumber('NG')
  phone_number?: string;

  @ApiProperty({
    description: 'User website link (personal or portfolio)',
    required: false,
    example: 'https://johndoe.com'
  })
  @IsOptional()
  @IsString()
  website_link?: string;

  @ApiProperty({
    description: 'Indicates if the user has completed onboarding',
    required: false,
    example: true
  })
  @IsOptional()
  @IsBoolean()
  is_onboarded?: boolean;

  @ApiProperty({
    description: 'User email address',
    required: false,
    example: 'john.doe@example.com'
  })
  @IsOptional()
  @IsEmail()
  email?: string;

  @ApiProperty({
    type: 'string',
    format: 'binary',
    description: 'User avatar image file. Maximum size: 7MB. Must be a file (not text). Use multipart/form-data',
    required: false,
    example: 'avatar.jpg'
  })
  @IsOptional()
  avatar?: Express.Multer.File | string;

  @ApiProperty({
    type: 'string',
    format: 'binary',
    description: 'User cover photo image file. Maximum size: 7MB. Must be a file (not text). Use multipart/form-data',
    required: false,
    example: 'cover.jpg'
  })
  @IsOptional()
  cover_photo?: Express.Multer.File | string;
}

export class CompleteUserDatabaseDTO {
  @ApiProperty({
    description: 'Unique ID of the user, generated by the database',
    example: '550e8400-e29b-41d4-a716-446655440000'
  })
  id: string;

  @ApiProperty({ 
    description: 'User email address',
    example: 'john.doe@example.com'
  })
  @IsEmail()
  email: string;

  @ApiProperty({ 
    description: 'Unique username chosen by the user',
    example: 'john_doe'
  })
  @IsString()
  username: string;

  @ApiProperty({
    description: 'Short bio or description about the user',
    required: false,
    example: 'Digital creator passionate about tech and design'
  })
  @IsOptional()
  @IsString()
  bio?: string;

  @ApiProperty({
    description:
      'Avatar image URL. The user uploads an image and the backend converts it to a URL using Cloudinary',
    required: false,
    example: 'https://res.cloudinary.com/cloudname/image/upload/v1234567890/avatar.jpg'
  })
  @IsOptional()
  @IsString()
  avatar?: string;

  @ApiProperty({
    description:
      'Cover photo URL. Uploaded by the user, stored in Cloudinary, and returned as a URL',
    required: false,
    example: 'https://res.cloudinary.com/cloudname/image/upload/v1234567890/cover.jpg'
  })
  @IsOptional()
  @IsString()
  cover_photo?: string;

  @ApiProperty({ 
    description: 'Display name of the user', 
    required: false,
    example: 'John Doe'
  })
  @IsOptional()
  @IsString()
  display_name?: string;

  @ApiProperty({
    description: 'User website link (personal or portfolio)',
    required: false,
    example: 'https://johndoe.com'
  })
  @IsOptional()
  @IsString()
  website_link?: string;

  @ApiProperty({
    description: 'User phone number in Nigerian format, optional',
    required: false,
    example: '+2348012345678'
  })
  @IsOptional()
  @IsPhoneNumber('NG')
  phone_number?: string;

  @ApiProperty({
    description: 'Indicates if the user has completed onboarding',
    example: true
  })
  @IsBoolean()
  is_onboarded: boolean;

  @ApiProperty({
    description:
      'Authentication provider: "local" for email/password, "google", "apple", etc.',
    example: 'local'
  })
  @IsString()
  auth_provider: string;

  @ApiProperty({
    description: 'Indicates if the user has verified their email',
    example: true
  })
  @IsBoolean()
  is_verified: boolean;

  @ApiProperty({
    description: 'Bank account details',
    required: false,
    example: {
      bank_name: 'Guaranty Trust Bank',
      account_name: 'John Chukwuma',
      account_number: '0123456789'
    }
  })
  bank_account?: {
    bank_name: string;
    account_name: string;
    account_number: string;
  };

  @ApiProperty({ 
    description: 'Date when the user was created',
    example: '2024-01-01T00:00:00.000Z'
  })
  @IsDate()
  created_at: Date;

  @ApiProperty({ 
    description: 'Date when the user was last updated',
    example: '2024-01-15T10:30:00.000Z'
  })
  @IsDate()
  updated_at: Date;
}

export class GenerateOtpDTO {
  @ApiProperty({ 
    description: 'Generate otp',
    example: 'john.doe@example.com'
  })
  @IsEmail()
  email: string;
}