import { ApiProperty } from '@nestjs/swagger';
import {
  IsNotEmpty,
  Length,
  Matches,
  IsOptional,
  IsString,
  IsPhoneNumber,
  IsDate,
  IsEmail,
  IsBoolean,
} from 'class-validator';
export class UpdatePayoutDetailsDTO {
  @ApiProperty({ description: 'The name of the bank' })
  @IsString()
  @IsNotEmpty()
  bankName: string;

  @ApiProperty({ description: 'The account number of the account holder' })
  @IsString()
  @IsNotEmpty()
  @Length(10, 10, { message: 'Account number must be 10 digits' })
  @Matches(/^\d+$/, { message: 'Account number must contain only digits' })
  accountNumber: string;

  @ApiProperty({ description: 'The name of the account holder' })
  @IsString()
  @IsNotEmpty()
  accountName: string;

  @ApiProperty({ description: 'one time password' })
  @IsString()
  @IsNotEmpty()
  otp: string;
}

export class UpdateUserDTO {
  @ApiProperty({
    description: 'Unique username chosen by the user',
    required: false,
  })
  @IsOptional()
  @IsString()
  username?: string;

  @ApiProperty({
    description: 'Display name of the user',
    required: false,
  })
  @IsOptional()
  @IsString()
  display_name?: string;

  @ApiProperty({
    description: 'Short bio or description about the user',
    required: false,
  })
  @IsOptional()
  @IsString()
  bio?: string;

  @ApiProperty({
    description: 'Phone number of the user in Nigerian format',
    required: false,
  })
  @IsOptional()
  @IsPhoneNumber('NG')
  phone_number?: string;
}

export class CompleteUserDatabaseDTO {
  @ApiProperty({
    description: 'Unique ID of the user, generated by the database',
  })
  id: string;

  @ApiProperty({ description: 'User email address' })
  @IsEmail()
  email: string;

  @ApiProperty({
    description: 'User password (hashed). Optional if using social login',
    required: false,
  })
  @IsOptional()
  password?: string;

  @ApiProperty({ description: 'Unique username chosen by the user' })
  @IsString()
  username: string;

  @ApiProperty({
    description: 'Short bio or description about the user',
    required: false,
  })
  @IsOptional()
  @IsString()
  bio?: string;

  @ApiProperty({
    description:
      'Avatar image URL. The user uploads an image and the backend converts it to a URL using Cloudinary',
    required: false,
  })
  @IsOptional()
  @IsString()
  avatar?: string;

  @ApiProperty({
    description:
      'Cover photo URL. Uploaded by the user, stored in Cloudinary, and returned as a URL',
    required: false,
  })
  @IsOptional()
  @IsString()
  cover_photo?: string;

  @ApiProperty({ description: 'Display name of the user', required: false })
  @IsOptional()
  @IsString()
  display_name?: string;

  @ApiProperty({
    description: 'User website link (personal or portfolio)',
    required: false,
  })
  @IsOptional()
  @IsString()
  website_link?: string;

  @ApiProperty({
    description: 'User phone number in Nigerian format, optional',
    required: false,
  })
  @IsOptional()
  @IsPhoneNumber('NG')
  phone_number?: string;

  @ApiProperty({
    description: 'Indicates if the user has completed onboarding',
  })
  @IsBoolean()
  is_onboarded: boolean;

  @ApiProperty({
    description:
      'Authentication provider: "local" for email/password, "google", "apple", etc.',
  })
  @IsString()
  auth_provider: string;

  @ApiProperty({
    description: 'Indicates if the user has verified their email',
  })
  @IsBoolean()
  is_verified: boolean;

  @ApiProperty({
    description: 'Bank account details',
    required: false,
    type: () => ({
      bank_name: { type: 'string' },
      account_name: { type: 'string' },
      account_number: { type: 'string' },
    }),
  })
  bank_account?: {
    bank_name: string;
    account_name: string;
    account_number: string;
  };

  @ApiProperty({ description: 'Date when the user was created' })
  @IsDate()
  created_at: Date;

  @ApiProperty({ description: 'Date when the user was last updated' })
  @IsDate()
  updated_at: Date;
}

export class GenerateOtpDTO {
  @ApiProperty({ description: 'Generate otp' })
  @IsEmail()
  email: string;
}
